version: '3.1'

services:
  goweb:
    build: .
    volumes:
      - .:/go/src/github.com/djordjev/docker-debugger
    security_opt:
      - seccomp:unconfined
    entrypoint:
      - ./bootstrap/docker-bootstrap-run.sh